<a href="https://colab.research.google.com/github/mellamonaranja/Natural-Language-Processing/blob/main/Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gensim

In [ ]:
import sklearn

In [25]:
import nltk

In [26]:
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nlt

True

In [ ]:
!pip install konlpy
import konlpy

     |████████████████████████████████| 19.4MB 1.3MB/s 
     |████████████████████████████████| 460kB 39.8MB/s 
     |████████████████████████████████| 92kB 9.6MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [ ]:
import pandas as pd
import pandas_profiling
data=pd.read_csv('./spam.csv', encoding='latin1')

In [ ]:
data[:5]

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [ ]:
from nltk.tokenize import word_tokenize
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
from nltk.tokenize import TreebankWordTokenizer

In [ ]:
s="Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."
t=TreebankWordTokenizer()
st=t.tokenize(s)
st

['Do',
 "n't",
 'be',
 'fooled',
 'by',
 'the',
 'dark',
 'sounding',
 'name',
 ',',
 'Mr.',
 'Jone',
 "'s",
 'Orphanage',
 'is',
 'as',
 'cheery',
 'as',
 'cheery',
 'goes',
 'for',
 'a',
 'pastry',
 'shop',
 '.']

In [ ]:
from nltk.tokenize import WordPunctTokenizer

In [ ]:
s="Good muffins cost $3.88\nin New York.  Please buy me\ntwo of them.\n\nThanks."
print(WordPunctTokenizer().tokenize(s))

['Good', 'muffins', 'cost', '$', '3', '.', '88', 'in', 'New', 'York', '.', 'Please', 'buy', 'me', 'two', 'of', 'them', '.', 'Thanks', '.']


In [ ]:
from nltk.tokenize import sent_tokenize
text="His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print(sent_tokenize(text))

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [ ]:
text="I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text))

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
text="I am actively looking for Ph.D. students. and you are a Ph.D. student."
x=word_tokenize(text)
pos_tag(x)

[('I', 'PRP'),
 ('am', 'VBP'),
 ('actively', 'RB'),
 ('looking', 'VBG'),
 ('for', 'IN'),
 ('Ph.D.', 'NNP'),
 ('students', 'NNS'),
 ('.', '.'),
 ('and', 'CC'),
 ('you', 'PRP'),
 ('are', 'VBP'),
 ('a', 'DT'),
 ('Ph.D.', 'NNP'),
 ('student', 'NN'),
 ('.', '.')]

In [ ]:
import re
text="I am actively looking for Ph.D. students. and you are a Ph.D. student."
sw=re.compile(r'\W*\b\w{1,2}\b')
print(sw.sub('',text))

 actively looking for. students. and you are. student.


In [ ]:
from nltk.stem import WordNetLemmatizer
n=WordNetLemmatizer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([n.lemmatize(w) for w in words])

['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [ ]:
n.lemmatize('dies','v')

'die'

In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
ps=PorterStemmer()
text="This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
wt=word_tokenize(text)
wt

['This',
 'was',
 'not',
 'the',
 'map',
 'we',
 'found',
 'in',
 'Billy',
 'Bones',
 "'s",
 'chest',
 ',',
 'but',
 'an',
 'accurate',
 'copy',
 ',',
 'complete',
 'in',
 'all',
 'things',
 '--',
 'names',
 'and',
 'heights',
 'and',
 'soundings',
 '--',
 'with',
 'the',
 'single',
 'exception',
 'of',
 'the',
 'red',
 'crosses',
 'and',
 'the',
 'written',
 'notes',
 '.']

In [ ]:
print([ps.stem(w) for w in wt])

['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [ ]:
w=['formalize', 'allowance', 'electricical']
print([ps.stem(i) for i in w])

['formal', 'allow', 'electric']


In [ ]:
from nltk.stem import LancasterStemmer
ls=LancasterStemmer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([ls.stem(w) for w in words])

['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')[:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [ ]:
sentence="Family is not an important thing. It's everything."
sw=set(stopwords.words('english'))
wt=word_tokenize(sentence)

result=[]
for w in wt:
  if w not in sw:
    result.append(w)
print(wt)
print(result)

['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [ ]:
import re
r=re.compile('ab.')
r.search('kkkabc')

<re.Match object; span=(3, 6), match='abc'>

In [ ]:
r.match('kkkabc')

In [ ]:
r.match('abccc')

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
text='Family is not an important thing. It\'s everything.'
re.split(' ',text)

['Family', 'is', 'not', 'an', 'important', 'thing.', "It's", 'everything.']

In [ ]:
text='Family is not an important thing. It\'s everything.'
re.split('\n',text)

["Family is not an important thing. It's everything."]

In [ ]:
text='Family +is +not +an important thing. It\'s everything.'
re.split('\+',text)

['Family ', 'is ', 'not ', "an important thing. It's everything."]

In [ ]:
text="""100 John    PROF
101 James   STUD
102 Mac   STUD"""
re.split('\s+',text)

['100', 'John', 'PROF', '101', 'James', 'STUD', '102', 'Mac', 'STUD']

In [ ]:
re.findall('\d+',text)

['100', '101', '102']

In [ ]:
re.findall('[A-Z][a-z]{2}',text)

['Joh', 'Jam', 'Mac']

In [ ]:
re.findall('[A-Z][a-z]+',text)

['John', 'James', 'Mac']

In [ ]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
text="A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [ ]:
text=sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
sw=set(stopwords.words('english'))
vb={}
sentences=[]

for i in text:
  sent=word_tokenize(i)
  result=[]

  for word in sent:
    word=word.lower()
    if word not in sw:
      if len(word)>2:
        result.append(word)
        if word not in vb:
          vb[word]=0
        vb[word]+=1
  sentences.append(result)
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [ ]:
vb

{'barber': 8,
 'crazy': 1,
 'driving': 1,
 'good': 1,
 'huge': 5,
 'keeping': 2,
 'kept': 4,
 'knew': 1,
 'mountain': 1,
 'person': 3,
 'secret': 6,
 'went': 1,
 'word': 2}

In [ ]:
vb_sorted=sorted(vb.items(), key=lambda x:x[1], reverse=True)
vb_sorted

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [ ]:
i=0
w_t_i={}

for (word,frequency) in vb_sorted:
  k=(word,frequency)
  print(k)
  if frequency>1:
    i=i+1
    w_t_i[word]=i
print(w_t_i)


('barber', 8)
('secret', 6)
('huge', 5)
('kept', 4)
('person', 3)
('word', 2)
('keeping', 2)
('good', 1)
('knew', 1)
('driving', 1)
('crazy', 1)
('went', 1)
('mountain', 1)
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [ ]:
vs=5
wf=[w for w,c in w_t_i.items() if c>=vs+1]
wf

[]

In [ ]:
for w in wf:
  del w_t_i[w]
w_t_i

{'barber': 1, 'huge': 3, 'kept': 4, 'secret': 2}

In [ ]:
len(w_t_i)

4

In [ ]:
w_t_i['OOV']=len(w_t_i)+1
encoded=[]
for s in sentences:
  temp=[]
  for w in s:
    try:
      temp.append(w_t_i[w])
    except KeyError:
      temp.append(w_t_i['OOV'])
  encoded.append(temp)
encoded

[[1, 6],
 [1, 6, 6],
 [1, 3, 6],
 [6, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [6, 6, 3, 2, 6, 1, 6],
 [1, 6, 3, 6]]

In [ ]:
from collections import Counter

In [ ]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [ ]:
import numpy as np
w_h=np.hstack(sentences)
w_h

array(['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge',
       'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret',
       'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept',
       'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge',
       'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge',
       'mountain'], dtype='<U8')

In [ ]:
w_f=Counter(w_h)
w_f

Counter({'barber': 8,
         'crazy': 1,
         'driving': 1,
         'good': 1,
         'huge': 5,
         'keeping': 2,
         'kept': 4,
         'knew': 1,
         'mountain': 1,
         'person': 3,
         'secret': 6,
         'went': 1,
         'word': 2})

In [ ]:
v5=w_f.most_common(vs)
v5

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
w_t_i={}
i=0
for (word,frequency) in v5:
  i=i+1
  w_t_i[word]=i
w_t_i

{'barber': 1, 'huge': 3, 'kept': 4, 'person': 5, 'secret': 2}

In [ ]:
from nltk import FreqDist
vocab=FreqDist(np.hstack(sentences))
vocab

FreqDist({'barber': 8,
          'crazy': 1,
          'driving': 1,
          'good': 1,
          'huge': 5,
          'keeping': 2,
          'kept': 4,
          'knew': 1,
          'mountain': 1,
          'person': 3,
          'secret': 6,
          'went': 1,
          'word': 2})

In [ ]:
vocab=vocab.most_common(vs)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
w_t_i={word[0]:index+1 for index,word in enumerate(vocab)}
w_t_i

{'barber': 1, 'huge': 3, 'kept': 4, 'person': 5, 'secret': 2}

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tok=Tokenizer()
tok.fit_on_texts(sentences)

In [ ]:
tok.word_index

{'barber': 1,
 'crazy': 11,
 'driving': 10,
 'good': 8,
 'huge': 3,
 'keeping': 7,
 'kept': 4,
 'knew': 9,
 'mountain': 13,
 'person': 5,
 'secret': 2,
 'went': 12,
 'word': 6}

In [ ]:
tok.word_counts

OrderedDict([('barber', 8),
             ('person', 3),
             ('good', 1),
             ('huge', 5),
             ('knew', 1),
             ('secret', 6),
             ('kept', 4),
             ('word', 2),
             ('keeping', 2),
             ('driving', 1),
             ('crazy', 1),
             ('went', 1),
             ('mountain', 1)])

In [ ]:
tok.texts_to_sequences(sentences)

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [ ]:
tok=Tokenizer(num_words=vs+1)
tok.fit_on_texts(sentences)
tok.texts_to_sequences(sentences)

[[1, 5],
 [1, 5],
 [1, 3, 5],
 [2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4],
 [1, 4],
 [1, 4, 2],
 [3, 2, 1],
 [1, 3]]

In [ ]:
tok.document_count

11

In [ ]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tok=Tokenizer()
tok.fit_on_texts(sentences)
tok.word_index

{'barber': 1,
 'crazy': 11,
 'driving': 10,
 'good': 8,
 'huge': 3,
 'keeping': 7,
 'kept': 4,
 'knew': 9,
 'mountain': 13,
 'person': 5,
 'secret': 2,
 'went': 12,
 'word': 6}

In [ ]:
tts=tok.texts_to_sequences(sentences)
tts

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [ ]:
len(tts)

11

In [ ]:
m_l=max(len(item) for item in tts)
m_l

7

In [ ]:
for i in tts:
  while len(i)<m_l:
    i.append(0)

np.array(tts)

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
tts=tok.texts_to_sequences(sentences)
tts

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [ ]:
pd=pad_sequences(tts)
pd

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [ ]:
pd=pad_sequences(tts,padding='post')
pd

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [ ]:
pd=pad_sequences(tts, padding='post', maxlen=5)
pd

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [ ]:
one_added=len(tok.word_index)+1
one_added

14

In [ ]:
pd=pad_sequences(tts, value=one_added)
pd

array([[14, 14, 14, 14, 14,  1,  5],
       [14, 14, 14, 14,  1,  8,  5],
       [14, 14, 14, 14,  1,  3,  5],
       [14, 14, 14, 14, 14,  9,  2],
       [14, 14, 14,  2,  4,  3,  2],
       [14, 14, 14, 14, 14,  3,  2],
       [14, 14, 14, 14,  1,  4,  6],
       [14, 14, 14, 14,  1,  4,  6],
       [14, 14, 14, 14,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [14, 14, 14,  1, 12,  3, 13]], dtype=int32)

In [ ]:
X,y=zip(['a',1],['b',2],['c',3])
X

('a', 'b', 'c')

In [ ]:
y

(1, 2, 3)

In [ ]:
sequences=(['a',1],['b',2],['c',3])
X,y=zip(*sequences)
X

('a', 'b', 'c')

In [ ]:
y

(1, 2, 3)

In [ ]:
import pandas as pd

values=[['A barber is a person. a barber is good person.',1],
['a barber is huge person.',0],
['he Knew A Secret!',0],
['The Secret He Kept is huge secret.',1]]
columns=['mail','existence and nonexistence']

df=pd.DataFrame(values,columns=columns)
df

mail  existence and nonexistence
0  A barber is a person. a barber is good person.                           1
1                        a barber is huge person.                           0
2                               he Knew A Secret!                           0
3              The Secret He Kept is huge secret.                           1

In [ ]:
X=df['mail']
y=df['existence and nonexistence']

In [ ]:
X

0    A barber is a person. a barber is good person.
1                          a barber is huge person.
2                                 he Knew A Secret!
3                The Secret He Kept is huge secret.
Name: mail, dtype: object

In [ ]:
y

0    1
1    0
2    0
3    1
Name: existence and nonexistence, dtype: int64

In [ ]:
import numpy as np
ar=np.arange(0,16).reshape(4,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
X=ar[:,:3]
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
y=ar[:,3]
y

array([ 3,  7, 11, 15])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=1234)

In [ ]:
X,y=np.arange(10).reshape(5,2), range(5)
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.33, random_state=1234)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[2 3]
 [4 5]
 [6 7]]
[[8 9]
 [0 1]]
[1, 2, 3]
[4, 0]


In [ ]:
X,y=np.arange(0,24).reshape(12,2), range(12)
print(X)
print(list(y))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
n_of_train=int(len(X)*0.8)
n_of_test=int(len(X)-n_of_train)
print(n_of_train)
print(n_of_test)

9
3


In [ ]:
X_train=X[:n_of_train]
y_train=y[:n_of_train]
X_test=X[n_of_train:]
y_test=y[n_of_train:]
print(X_train,'\n')
print(X_test,'\n')
print(y_train,'\n')
print(y_test)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]] 

[[18 19]
 [20 21]
 [22 23]] 

range(0, 9) 

range(9, 12)


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
corpus=['you know I want your love. because I love you.']
cv=CountVectorizer()
print(cv.fit_transform(corpus).toarray())
print(cv.vocabulary_)

[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [ ]:
from nltk.corpus import stopwords
text=["Family is not an important thing. It's everything."]
# sw=set(stopwords.words('english'))
cv=CountVectorizer(stopwords.words('english'))
print(cv.fit_transform(text).toarray())
print(cv.vocabulary_)

[[1 1 1 1 1 1 1 1]]
{'family': 2, 'is': 4, 'not': 6, 'an': 0, 'important': 3, 'thing': 7, 'it': 5, 'everything': 1}


In [ ]:
text=["Family is not an important thing. It's everything."]
cv=CountVectorizer(stop_words='english')
print(cv.fit_transform(text).toarray())
print(cv.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [ ]:
import pandas as pd
from math import log

In [ ]:
docs=['This movie is very scary and long',
      'This movie is not scary and is slow',
      'This movie is spooky and good']

vocab=list(set(w for doc in docs for w in doc.split()))
vocab

['is',
 'slow',
 'and',
 'This',
 'not',
 'spooky',
 'good',
 'very',
 'scary',
 'movie',
 'long']

In [ ]:
vocab.sort()

In [ ]:
N=len(docs)

def tf(t,d):
  return d.count(t)

def idf(t):
  df=0
  for doc in docs:
    df+=t in doc
  return log(N/(1+df))

def tfidf(t,d):
  return tf(t,d)*idf(t)

result=[]
for i in range(N):
  result.append([])
  d=docs[i]
  for j in range(len(vocab)):
    t=vocab[j]
    result[-1].append(tf(t,d))

print(pd.DataFrame(result, columns=vocab))
print(result)

   This  and  good  is  long  movie  not  scary  slow  spooky  very
0     1    1     0   2     1      1    0      1     0       0     1
1     1    1     0   3     0      1    1      1     1       0     0
2     1    1     1   2     0      1    0      0     0       1     0
[[1, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1], [1, 1, 0, 3, 0, 1, 1, 1, 1, 0, 0], [1, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0]]


In [ ]:
result=[]
for j in range(len(vocab)):
  t=vocab[j]
  result.append(idf(t))

pd.DataFrame(result, index=vocab, columns=['IDF'])

IDF
This   -0.287682
and    -0.287682
good    0.405465
is     -0.287682
long    0.405465
movie  -0.287682
not     0.405465
scary   0.000000
slow    0.405465
spooky  0.405465
very    0.405465

In [ ]:
result=[]
for i in range(N):
  result.append([])
  d=docs[i]
  for j in range(len(vocab)):
    t=vocab[j]
    result[-1].append(tfidf)
pd.DataFrame(result, columns=vocab)

This  ...                                very
0  <function tfidf at 0x7f5cb099e7a0>  ...  <function tfidf at 0x7f5cb099e7a0>
1  <function tfidf at 0x7f5cb099e7a0>  ...  <function tfidf at 0x7f5cb099e7a0>
2  <function tfidf at 0x7f5cb099e7a0>  ...  <function tfidf at 0x7f5cb099e7a0>

[3 rows x 11 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer 
corpus=['you know I want your love',
    'I like you',
    'what should I do ',]
cv=CountVectorizer()
print(cv.fit_transform(corpus).toarray())
print(cv.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
corpus=['you know I want your love',
    'I like you',
    'what should I do ',]
tfidf=TfidfVectorizer().fit(corpus)
print(tfidf.transform(corpus).toarray())
print(tfidf.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
from numpy import dot
from numpy.linalg import norm
import numpy as np
def cos_sim(A,B):
  return dot(A,B)/(norm(A)*norm(B))

In [ ]:
doc1=np.array([0,1,1,1])
doc2=np.array([1,0,1,1])
doc3=np.array([2,0,2,2])

In [ ]:
print(cos_sim(doc1,doc2))
print(cos_sim(doc1,doc3))
print(cos_sim(doc2,doc3))

0.6666666666666667
0.6666666666666667
1.0000000000000002


In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [ ]:
data=pd.read_csv('./movies_metadata.csv', low_memory=False)
data.head(2)

adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0

[2 rows x 24 columns]

In [ ]:
data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
data.count(axis=0)

adult                    30943
belongs_to_collection     3460
budget                   30943
genres                   30943
homepage                  5032
id                       30943
imdb_id                  30931
original_language        30940
original_title           30943
overview                 30572
popularity               30939
poster_path              30774
production_companies     30941
production_countries     30941
release_date             30910
revenue                  30939
runtime                  30856
spoken_languages         30939
status                   30894
tagline                  16183
title                    30938
video                    30938
vote_average             30938
vote_count               30938
dtype: int64

In [ ]:
data=data.head(20000)

In [ ]:
data['overview'].isnull().sum()

16

In [ ]:
data['overview']=data['overview'].fillna('')

In [ ]:
data['overview'].isnull().sum()

0

In [ ]:
data['overview'][:5]

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [ ]:
tfidf=TfidfVectorizer(stop_words='english')
tt=tfidf.fit_transform(data['overview'])

print(tt.shape)

(2000, 13918)


In [ ]:
tt_array=tfidf.fit_transform(data['overview']).toarray()
print(tt_array[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
tt[:5]

<5x13918 sparse matrix of type '<class 'numpy.float64'>'
	with 135 stored elements in Compressed Sparse Row format>

In [ ]:
cos_sim=linear_kernel(tt, tt)
indices=pd.Series(data.index, index=data['title']).drop_duplicates()
print(indices.head())

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64


In [ ]:
cos_sim[:5]

array([[1.        , 0.01729311, 0.        , ..., 0.        , 0.        ,
        0.02241016],
       [0.01729311, 1.        , 0.04843596, ..., 0.        , 0.        ,
        0.01222168],
       [0.        , 0.04843596, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.01530574,
        0.        ],
       [0.        , 0.        , 0.02726241, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
idx=indices['Jumanji']
idx

1

In [ ]:
def get_recom(title, cos_sim=cos_sim):
  idx=indices[title]
  sim_scores=list(enumerate(cos_sim[idx]))
  sim_scores=sorted(sim_scores, key=lambda x:x[1], reverse=True)
  sim_scores=sim_scores[1:11]
  movie_indices=[i[0] for i in sim_scores]
  return data['title'].iloc[movie_indices]

In [ ]:
get_recom('Toy Story')

1071       Rebel Without a Cause
1932                   Condorman
485                       Malice
448            For Love or Money
1032               The Sunchaser
1884              Child's Play 3
748           I Shot Andy Warhol
591              Window to Paris
314     The Shawshank Redemption
180                 Mute Witness
Name: title, dtype: object

In [ ]:
sorted('This is a test string'.split())

['This', 'a', 'is', 'string', 'test']

In [ ]:
sorted('This is a test string'.split(),key=str.lower)

['a', 'is', 'string', 'test', 'This']

In [ ]:
st=[('john', 'A', 15),('jane', 'B', 12),('dave', 'B', 10)]
sorted(st,key=lambda student:student[2])

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]

In [ ]:
st=[('john', 'A', 15),('jane', 'B', 12),('dave', 'B', 10)]
sorted(st,key=lambda student:student[2], reverse=True)

[('john', 'A', 15), ('jane', 'B', 12), ('dave', 'B', 10)]

In [ ]:
pd.Series(data.index)

0          0
1          1
2          2
3          3
4          4
        ... 
1995    1995
1996    1996
1997    1997
1998    1998
1999    1999
Length: 2000, dtype: int64

In [ ]:
data['title'].head()

0                      Toy Story
1                        Jumanji
2               Grumpier Old Men
3              Waiting to Exhale
4    Father of the Bride Part II
Name: title, dtype: object

In [ ]:
import numpy as np

In [ ]:
def distance(x,y):
  return np.sqrt(np.sum((x-y)**2))

doc1=np.array((2,3,0,1))
doc2 = np.array((1,2,3,1))
doc3 = np.array((2,1,2,2))
docQ = np.array((1,1,0,1))

print(distance(doc1,docQ))
print(distance(doc2,docQ))
print(distance(doc3,docQ))

2.23606797749979
3.1622776601683795
2.449489742783178


In [ ]:
doc1='apple banana everyone like likey watch card holder'
doc2='apple banana coupon passport love you'

In [ ]:
tok1=doc1.split()
tok2=doc2.split()
print(tok1)
print(tok2)

['apple', 'banana', 'everyone', 'like', 'likey', 'watch', 'card', 'holder']
['apple', 'banana', 'coupon', 'passport', 'love', 'you']


In [ ]:
union=set(tok1).union(set(tok2))
union

{'apple',
 'banana',
 'card',
 'coupon',
 'everyone',
 'holder',
 'like',
 'likey',
 'love',
 'passport',
 'watch',
 'you'}

In [ ]:
intersection=set(tok1).intersection(set(tok2))
intersection

{'apple', 'banana'}

In [ ]:
len(intersection)/len(union)

0.16666666666666666

In [ ]:
import numpy as np


In [ ]:
A=np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

In [ ]:
U,s,VT=np.linalg.svd(a,full_matrices=True)
print(U.round(2),'\n')
print(s.round(2),'\n')
print(VT.round(2))

[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]] 

[2.69 2.05 1.73 0.77] 

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
S=np.zeros((4,9))
print(S,'\n')
S[:4,:4]

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]] 



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.diag(s)

array([[2.68731789, 0.        , 0.        , 0.        ],
       [0.        , 2.04508425, 0.        , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 0.        , 0.77197992]])

In [ ]:
S[:4,:4]=np.diag(s)
print(S.round(2))

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


In [ ]:
S=S[:2,:2]
U=U[:,:2]
VT=VT[:2,:]

In [ ]:
A_prime=np.dot(np.dot(U,S),VT)
print(A,'\n')
print(A_prime)

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]] 

[[ 1.06294170e-16 -1.68331693e-01 -1.68331693e-01  1.07644409e+00
   1.18172804e-01  6.21607906e-01  1.07644409e+00 -2.82373759e-17
  -2.82373759e-17]
 [ 1.58890262e-16  2.02338650e-01  2.02338650e-01  9.08112402e-01
   8.57953513e-01  4.54836189e-01  9.08112402e-01  3.39419894e-17
   3.39419894e-17]
 [ 1.90387008e-16  9.25115881e-01  9.25115881e-01  3.40069574e-02
   2.05257041e+00 -1.68331693e-01  3.40069574e-02  1.55186730e-16
   1.55186730e-16]
 [ 2.14417617e-32  8.73702294e-17  8.73702294e-17  2.97991578e-17
   2.05923923e-16 -1.38430638e-18  2.97991578e-17  1.46562182e-32
   1.46562182e-32]]


In [ ]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups

In [ ]:
dataset=fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers','quites'))

In [ ]:
type(dataset)

sklearn.utils.Bunch

In [ ]:
doc=dataset.data
len(doc)

11314

In [ ]:
doc[1]

"James Hogan writes:\n\ntimmbake@mcl.ucsb.edu (Bake Timmons) writes:\n>>Jim Hogan quips:\n\n>>... (summary of Jim's stuff)\n\n>>Jim, I'm afraid _you've_ missed the point.\n\n>>>Thus, I think you'll have to admit that  atheists have a lot\n>>more up their sleeve than you might have suspected.\n\n>>Nah.  I will encourage people to learn about atheism to see how little atheists\n>>have up their sleeves.  Whatever I might have suspected is actually quite\n>>meager.  If you want I'll send them your address to learn less about your\n>>faith.\n\n>Faith?\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n>>>Fine, but why do these people shoot themselves in the foot and mock\n>>>the idea of a God?  ....\n\n>>>I hope you understand now.\n\n>>Yes, Jim.  I do understand now.  Thank you for providing some healthy sarcasm\n>>that would have dispelled any sympathies I would have had for

In [ ]:
dataset.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [ ]:
df=pd.DataFrame({'document':doc})
df

document
0      Well i'm not sure about the story nad it did s...
1      James Hogan writes:\n\ntimmbake@mcl.ucsb.edu (...
2      Although I realize that principle is not one o...
3      Notwithstanding all the legitimate fuss about ...
4      Well, I will have to change the scoring on my ...
...                                                  ...
11309  Danny Rubenstein, an Israeli journalist, will ...
11310  ron.roth@rose.com (ron roth) writes:\n\n|JB>  ...
11311  In article <1qn6tqINNmnf@senator-bedfellow.MIT...
11312  I used HP DeskJet with Orange Micros Grappler ...
11313  In article <15APR199311534452@rosie.uh.edu> st...

[11314 rows x 1 columns]

In [ ]:
df['clean']=df['document'].str.replace("[^a-zA-Z]", " ")
df['clean']=df['clean'].apply(lambda x:' '.join(w for w in x.split() if len(w)>3))
df['clean']=df['clean'].apply(lambda x:x.lower())

In [ ]:
df['clean'][1]

'james hogan writes timmbake ucsb bake timmons writes hogan quips summary stuff afraid missed point thus think have admit that atheists have more their sleeve than might have suspected will encourage people learn about atheism little atheists have their sleeves whatever might have suspected actually quite meager want send them your address learn less about your faith faith yeah expect people read actually accept hard atheism need little leap faith jimmy your logic runs steam fine these people shoot themselves foot mock idea hope understand understand thank providing some healthy sarcasm that would have dispelled sympathies would have your faith bake real glad detected sarcasm angle really bummin that getting your sympathy still your inclined have sympathy somebody faith might religion newsgroups just careful over there though make believe whispering your here they delusional sorry pity sorry that have these feelings denial about faith need well just pretend that will happily ever after

In [ ]:
from nltk.corpus import stopwords

In [ ]:
sw=stopwords.words('english')
tok_doc=df['clean'].apply(lambda x:x.split())
tok_doc=tok_doc.apply(lambda x:[i for i in x if i not in sw])

In [ ]:
tok_doc[1]

['james',
 'hogan',
 'writes',
 'timmbake',
 'ucsb',
 'bake',
 'timmons',
 'writes',
 'hogan',
 'quips',
 'summary',
 'stuff',
 'afraid',
 'missed',
 'point',
 'thus',
 'think',
 'admit',
 'atheists',
 'sleeve',
 'might',
 'suspected',
 'encourage',
 'people',
 'learn',
 'atheism',
 'little',
 'atheists',
 'sleeves',
 'whatever',
 'might',
 'suspected',
 'actually',
 'quite',
 'meager',
 'want',
 'send',
 'address',
 'learn',
 'less',
 'faith',
 'faith',
 'yeah',
 'expect',
 'people',
 'read',
 'actually',
 'accept',
 'hard',
 'atheism',
 'need',
 'little',
 'leap',
 'faith',
 'jimmy',
 'logic',
 'runs',
 'steam',
 'fine',
 'people',
 'shoot',
 'foot',
 'mock',
 'idea',
 'hope',
 'understand',
 'understand',
 'thank',
 'providing',
 'healthy',
 'sarcasm',
 'would',
 'dispelled',
 'sympathies',
 'would',
 'faith',
 'bake',
 'real',
 'glad',
 'detected',
 'sarcasm',
 'angle',
 'really',
 'bummin',
 'getting',
 'sympathy',
 'still',
 'inclined',
 'sympathy',
 'somebody',
 'faith',
 'might

In [ ]:
detok=[]
for i in range(len(df)):
  t=' '.join(tok_doc[i])
  detok.append(t)

df['clean']=detok
df['clean'][1]

'james hogan writes timmbake ucsb bake timmons writes hogan quips summary stuff afraid missed point thus think admit atheists sleeve might suspected encourage people learn atheism little atheists sleeves whatever might suspected actually quite meager want send address learn less faith faith yeah expect people read actually accept hard atheism need little leap faith jimmy logic runs steam fine people shoot foot mock idea hope understand understand thank providing healthy sarcasm would dispelled sympathies would faith bake real glad detected sarcasm angle really bummin getting sympathy still inclined sympathy somebody faith might religion newsgroups careful though make believe whispering delusional sorry pity sorry feelings denial faith need well pretend happily ever anyway maybe start newsgroup atheist hard bummin much good bake slim deleted bake forget flintstone chewables bake timmons'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vt=TfidfVectorizer(stop_words='english',max_features=1000, max_df=0.5, smooth_idf=True)
X=vt.fit_transform(df['clean'])
X.shape


(11314, 1000)

In [ ]:
from sklearn.decomposition import TruncatedSVD 
svd_model=TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_)

20

In [ ]:
np.shape(svd_model.components_)

(20, 1000)

In [ ]:
terms=vt.get_feature_names()


In [ ]:
def get_topics(components, feature_names, n=5):
  for idx,topic in enumerate(components):
    print('topic %d:'%(idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n-1:-1]])
get_topics(svd_model.components_,terms)

topic 1: [('article', 0.22), ('like', 0.19), ('people', 0.18), ('know', 0.18), ('think', 0.16)]
topic 2: [('windows', 0.35), ('thanks', 0.26), ('card', 0.19), ('file', 0.16), ('drive', 0.16)]
topic 3: [('game', 0.38), ('team', 0.36), ('games', 0.25), ('year', 0.25), ('season', 0.2)]
topic 4: [('drive', 0.59), ('scsi', 0.27), ('drives', 0.16), ('hard', 0.16), ('disk', 0.15)]
topic 5: [('thanks', 0.46), ('mail', 0.29), ('advance', 0.18), ('know', 0.15), ('email', 0.15)]
topic 6: [('chip', 0.25), ('encryption', 0.21), ('government', 0.2), ('clipper', 0.2), ('space', 0.16)]
topic 7: [('drive', 0.36), ('file', 0.19), ('files', 0.17), ('scsi', 0.14), ('game', 0.14)]
topic 8: [('card', 0.43), ('chip', 0.18), ('video', 0.18), ('people', 0.15), ('game', 0.14)]
topic 9: [('article', 0.45), ('israel', 0.33), ('israeli', 0.22), ('card', 0.19), ('jews', 0.15)]
topic 10: [('space', 0.38), ('sale', 0.23), ('nasa', 0.22), ('offer', 0.14), ('israel', 0.14)]
topic 11: [('article', 0.35), ('space', 0.19)

In [ ]:
a=np.array([5,2,7])
a.argsort()

array([1, 0, 2])

In [ ]:
tok_doc[:5]

0    [well, sure, story, seem, biased, disagree, st...
1    [james, hogan, writes, timmbake, ucsb, bake, t...
2    [although, realize, principle, strongest, poin...
3    [notwithstanding, legitimate, fuss, proposal, ...
4    [well, change, scoring, playoff, pool, unfortu...
Name: clean, dtype: object

In [ ]:
from gensim import corpora

In [ ]:
Dict=corpora.Dictionary(tok_doc)
corpus=[Dict.doc2bow(text) for text in tok_doc]
Dict[33]

'races'

In [ ]:
len(Dict)

70648

In [ ]:
import gensim

In [ ]:
NUM_TOPICS=20
ldamodel=gensim.models.ldamodel.LdaModel(corpus, num_topics=NUM_TOPICS, id2word=Dict, passes=15)
topics=ldamodel.print_topics(num_words=4)
for topic in topics:
  print(topic)

(0, '0.007*"people" + 0.007*"government" + 0.006*"president" + 0.006*"would"')
(1, '0.011*"would" + 0.007*"like" + 0.006*"used" + 0.006*"system"')
(2, '0.010*"homosexual" + 0.007*"sexual" + 0.007*"homosexuals" + 0.007*"cramer"')
(3, '0.009*"nrhj" + 0.006*"wwiz" + 0.005*"bxom" + 0.005*"gizw"')
(4, '0.011*"available" + 0.010*"information" + 0.009*"mail" + 0.009*"software"')
(5, '0.009*"writes" + 0.008*"smith" + 0.007*"john" + 0.006*"article"')
(6, '0.023*"israel" + 0.016*"jews" + 0.015*"israeli" + 0.009*"arab"')
(7, '0.018*"turkish" + 0.012*"turkey" + 0.009*"turks" + 0.009*"fire"')
(8, '0.025*"space" + 0.013*"nasa" + 0.006*"ground" + 0.005*"launch"')
(9, '0.013*"jesus" + 0.008*"people" + 0.008*"said" + 0.006*"armenian"')
(10, '0.021*"writes" + 0.018*"article" + 0.008*"braves" + 0.006*"morris"')
(11, '0.011*"would" + 0.011*"like" + 0.010*"writes" + 0.009*"article"')
(12, '0.014*"game" + 0.014*"team" + 0.011*"year" + 0.010*"games"')
(13, '0.018*"windows" + 0.013*"thanks" + 0.012*"know" + 0

In [ ]:
!pip install pyLDAvis

     |████████████████████████████████| 1.7MB 8.4MB/s 
  Created wheel for pyLDAvis: filename=pyLDAvis-3.2.2-py2.py3-none-any.whl size=135593 sha256=ebd9c1fb011c987d3418d5035ca6662a946beda1864c44dfb227df041ac3040e
  Stored in directory: /root/.cache/pip/wheels/74/df/b6/97234c8446a43be05c9a8687ee0db1f1b5ade5f27729187eae
Successfully built pyLDAvis


In [ ]:
import pyLDAvis.gensim

In [ ]:
pyLDAvis.enable_notebook()
vis=pyLDAvis.gensim.prepare(ldamodel,corpus,Dict)
pyLDAvis.display(vis)

In [ ]:
for i,topic_list in enumerate(ldamodel[corpus]):
  if i==5:
    break
  print(i,topic_list)

0 [(6, 0.26067126), (9, 0.11920204), (11, 0.47745645), (18, 0.129767)]
1 [(1, 0.034134515), (6, 0.044855535), (7, 0.14990851), (11, 0.25653347), (17, 0.035405792), (18, 0.47377756)]
2 [(6, 0.51913553), (11, 0.34204835), (18, 0.12510644)]
3 [(8, 0.035031598), (9, 0.080692686), (11, 0.06660855), (14, 0.10093034), (16, 0.4430262), (17, 0.07132838), (18, 0.19268075)]
4 [(9, 0.24132627), (12, 0.72534037)]


In [ ]:
def topictable(ldamodel, corpus):
  t_t=pd.DataFrame()

  for i,topic_list in enumerate(ldamodel[corpus]):
    doc=topic_list[0] if ldamodel.per_word_topics else topic_list 
    doc=sorted(doc, key=lambda x:(x[1]), reverse=True)
    for j,(t_n,p_t) in enumerate(doc):
      if j==0:
        t_t=t_t.append(pd.Series([int(t_n), round(p_t,4), topic_list]), ignore_index=True)
      else:
        break 
  return t_t

In [ ]:
tt=topictable(ldamodel, corpus)
tt=tt.reset_index()
tt.columns=['num','high prop topic','highest topic prop','each topic prop']
tt[:3]

KeyboardInterrupt: ignored

In [1]:
import pandas as pd

In [4]:
df=pd.DataFrame([[1,2],[3,4]],columns=list('ab'))
df

a  b
0  1  2
1  3  4

In [20]:
import numpy as np
df.apply(np.sqrt)

a         b
0  1.000000  1.414214
1  1.732051  2.000000

In [47]:
df.apply(np.sum, axis='index')

a    4
b    6
dtype: int64

In [22]:
df.apply(np.sum, axis=1)

0    3
1    7
dtype: int64

In [7]:
df2=pd.DataFrame([[5,6],[7,8]],columns=list('ab'))
df2

a  b
0  5  6
1  7  8

In [8]:
df.append(df2)

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [9]:
df.append(df2, ignore_index=False)

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [10]:
df.append(df2, ignore_index=True)

a  b
0  1  2
1  3  4
2  5  6
3  7  8

In [11]:
import urllib.request

In [13]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/franciscadias/data/master/abcnews-date-text.csv", filename="abcnews-date-text.csv")

('abcnews-date-text.csv', <http.client.HTTPMessage at 0x7fac23398a10>)

In [14]:
data=pd.read_csv("abcnews-date-text.csv", error_bad_lines=False)

In [15]:
len(data)

1082168

In [16]:
data.head(5)

publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers

In [17]:
text=data[['headline_text']]
text.head(5)

headline_text
0  aba decides against community broadcasting lic...
1     act fire witnesses must be aware of defamation
2     a g calls for infrastructure protection summit
3           air nz staff in aust strike for pay rise
4      air nz strike to affect australian travellers

In [18]:
import nltk

In [27]:
text['headline_text']=text.apply(lambda row:nltk.word_tokenize(row['headline_text']),axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [31]:
text=text[:1000]
text.head()

headline_text
0  [aba, decides, against, community, broadcastin...
1  [act, fire, witnesses, must, be, aware, of, de...
2  [a, g, calls, for, infrastructure, protection,...
3  [air, nz, staff, in, aust, strike, for, pay, r...
4  [air, nz, strike, to, affect, australian, trav...

In [32]:
from nltk.corpus import stopwords
stop=stopwords.words('english')
text['headline_text']=text.apply(lambda x:[word for word in x if word not in (stop)])
text.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


headline_text
0  [aba, decides, against, community, broadcastin...
1  [act, fire, witnesses, must, be, aware, of, de...
2  [a, g, calls, for, infrastructure, protection,...
3  [air, nz, staff, in, aust, strike, for, pay, r...
4  [air, nz, strike, to, affect, australian, trav...

In [33]:
from nltk.stem import WordNetLemmatizer

In [34]:
text['headline_text']=text['headline_text'].apply(lambda x:[WordNetLemmatizer().lemmatize(word, pos='v') for word in x])
text.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


headline_text
0  [aba, decide, against, community, broadcast, l...
1  [act, fire, witness, must, be, aware, of, defa...
2  [a, g, call, for, infrastructure, protection, ...
3  [air, nz, staff, in, aust, strike, for, pay, r...
4  [air, nz, strike, to, affect, australian, trav...

In [36]:
morethan3=text['headline_text'].apply(lambda x:[word for word in x if len(word)>3])
morethan3.head()

0    [decide, against, community, broadcast, licence]
1            [fire, witness, must, aware, defamation]
2          [call, infrastructure, protection, summit]
3                         [staff, aust, strike, rise]
4            [strike, affect, australian, travellers]
Name: headline_text, dtype: object

In [37]:
detoken=[]
for i in range(len(text)):
  t=' '.join(morethan3[i])
  detoken.append(t)

text['headline_text']=detoken

text['headline_text'].head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0    decide against community broadcast licence
1            fire witness must aware defamation
2         call infrastructure protection summit
3                        staff aust strike rise
4           strike affect australian travellers
Name: headline_text, dtype: object

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(stop_words='english', max_features=100)
X=tv.fit_transform(text['headline_text'])
X.shape

(1000, 100)

In [42]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model=LatentDirichletAllocation(n_components=10, learning_method='online', random_state=77,max_iter=1)
X_model=lda_model.fit_transform(X)
print(lda_model.components_)
print(lda_model.components_.shape)

[[ 0.3358331   5.56782497  0.34221003  0.28275237  5.48240831  0.3119301
   0.35470864  0.33817633  0.3269963   0.64531787  0.32726252  0.38266315
   0.3339254   0.37787722  5.86197994  0.3166976   0.30001315  0.29192143
   0.30729948  0.86554199  0.37724812  0.32544583  0.32788734  0.41306404
   1.17124429  0.33186005  0.30963476  0.35352857  0.3411747   0.35191888
   0.35887841  0.32973723  0.30547822  0.38109213  4.65113158  5.21188014
   0.35056566  0.38182056  0.32118926  0.36187565  0.33497484  0.3276451
   0.43254153  0.3781348   0.355314    0.46670688  0.31272088  0.30679167
   0.59645106  0.32662297  0.32467345  2.11803598  0.61077155  0.31695809
   7.38241514  0.35053162  0.32671108  0.32794021  0.31685418  0.33745974
   0.31690301  0.3634485   0.28359515  0.32965119  0.32929919  0.35210313
   0.34845615  0.42237662  0.63727769  0.30215572  2.54588593  0.29180226
   2.02653441  0.28096116  0.35539201  0.67040165  7.47929839  0.64788199
   0.29274375  1.06165963  0.30099996  0

In [46]:
terms=tv.get_feature_names()

def get_topics(components, feature_names,n=5):
  for idx,topic in enumerate(components):
    print('topic %d:'%(idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n-1:-1]])
get_topics(lda_model.components_,terms)

topic 1: [('record', 7.48), ('lead', 7.38), ('club', 5.86), ('action', 5.57), ('attack', 5.48)]
topic 2: [('police', 12.91), ('rain', 6.89), ('jail', 6.48), ('offer', 6.14), ('kill', 5.65)]
topic 3: [('claim', 12.03), ('talk', 7.39), ('iraqi', 7.27), ('race', 7.26), ('defend', 6.11)]
topic 4: [('court', 11.27), ('murder', 8.14), ('face', 7.36), ('drought', 7.01), ('price', 6.19)]
topic 5: [('iraq', 12.44), ('water', 8.92), ('warn', 6.95), ('expect', 6.17), ('death', 6.08)]
topic 6: [('warne', 7.55), ('continue', 7.27), ('charge', 6.98), ('coast', 6.11), ('turkey', 5.91)]
topic 7: [('report', 6.68), ('anti', 6.28), ('make', 5.48), ('zimbabwe', 5.44), ('seek', 5.1)]
topic 8: [('break', 6.42), ('stay', 4.94), ('patterson', 4.63), ('raid', 4.17), ('health', 3.98)]
topic 9: [('council', 9.84), ('govt', 7.74), ('aust', 4.53), ('cost', 4.44), ('decision', 3.68)]
topic 10: [('plan', 16.21), ('match', 5.59), ('urge', 5.52), ('england', 5.39), ('community', 4.75)]
